Repository Devanik21/ISRO_Mining_Site_FINAL_APP, pull requests merged in 2024-10, with the labels that each got.

#38 Changed the deep learning framework from tensorflow to pytorch
  pytorch_Isro_space_mining.ipynb
Labels: gssoc-ext, level2

#43 done enhancements in readme file
  README.md
Labels: gssoc-ext

#46 added contibutors.md, fixed the link to contributors.md in readme.md
  CONTRIBUTORS.md
  Contributing.md
  README.md
Labels: gssoc-ext, level1

#50 Create auto-comment-on-closing.yml
  .github/workflows/auto-comment-on-closing.yml
Labels: enhancement, gssoc-ext, level1

#61 Added Charts for better understanding for Rocks Classification
  Rocks_Classification/3D_ViewChartsImages/chart1.png
  Rocks_Classification/3D_ViewChartsImages/chart2.png
  Rocks_Classification/3D_ViewChartsImages/chart3.png
  Rocks_Classification/3D_ViewChartsImages/chart4.png
  Rocks_Classification/ChartforRocksClassification.ipynb
Labels: enhancement, gssoc-ext, level2

#60 Adding Dockerfile and docker-compose.yml files (Tested)
  .dockerignore
  Dockerfile
  docker-compose.debug.yml
  docker-compose.yml
  test-docker.sh
Labels: documentation, help wanted, question, gssoc-ext, level3

#63 Update 3_📊 Visualize.py
  pages/3_📊 Visualize.py
Labels: gssoc-ext, level2

#67 [README] Github Stats Updated
  .idea/.gitignore
  .idea/ISRO_Mining_Site_FINAL_APP.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  README.md
Labels: gssoc-ext, level1, hactoberfest

#70 New eda for Isro space mining
  EDA/EDA_ISRO_SPACE_MINING.ipynb
  EDA_ISRO_SPACE_MINING.ipynb
Labels: enhancement, gssoc-ext, level2
